baseurl = "http://dsk.mn/"
languageCode = "en-us"
title = "I/O"

pygmentsuseclasses = true
PygmentsLineNos = true
disqusShortname = "dsk-mn"

[Params]
PublishedDateFormat = "2006-01-02"
TimestampFormat = "2006-01-02T15:04:05Z07:00"

Auther = "minodisk"
Profile = "UX/UI Engineer"
EmailAddress = "daisuke.mino@gmail.com"
TwitterId = "minodisk"
GooglePlusId = "117361242608765720862"
GitHubId = "minodisk"
GoogleAnaliticsId = "UA-48719488-1"
