baseurl = "http://dsk.mn/"
languageCode = "en-us"
title = "I/O"

pygmentsuseclasses = true
disqusShortname = "dsk-mn"

[Params]
Auther = "minodisk"
EmailAddress = "daisuke.mino@gmail.com"
TwitterId = "minodisk"
GooglePlusId = "117361242608765720862"
GitHubId = "minodisk"

PublishedDateFormat = "2006-01-02"
GoogleAnaliticsId = "UA-48719488-1"
